name: Helm Chart - 0 Test and Lint

description: |
  Lint and test Helm chart.

on:
  pull_request:
    branches:
      - main
    paths:
      - "chart/**"
      - ".github/workflows/chart-*.yml"
  push:
    branches:
      - main
    paths:
      - "chart/**"
      - ".github/workflows/chart-*.yml"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  CHART_PATH: chart/infra-eye

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v5
        with:
          version: "latest"

      - name: Lint Helm chart
        run: |
          helm lint ${{ env.CHART_PATH }}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v5
        with:
          version: "latest"

      - name: Helm unittest
        run: |
          helm plugin install  --verify=false https://github.com/helm-unittest/helm-unittest
          helm unittest ${{ env.CHART_PATH }}

      - name: Helm template dry-run
        run: |
          helm template test-release ${{ env.CHART_PATH }}

  build-and-push:
    runs-on: ubuntu-latest
    needs: [test, lint]
    outputs:
      bumpVersion: ${{ steps.changes.outputs.bumpVersion }}
      createTag: ${{ steps.changes.outputs.createTag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v5
        with:
          version: "latest"

      - name: Package Helm chart
        run: |
          helm package ${{ env.CHART_PATH }} --destination .

      - name: Detect if only Chart.yaml changed
        id: changes
        run: |
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "Changed files: $CHANGED"
          ## if on PR both is false
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo "On pull request, skipping version bump and tag creation."
            echo "bumpVersion=false" >> $GITHUB_OUTPUT
            echo "createTag=false" >> $GITHUB_OUTPUT
          elif [[ "$CHANGED" == "${{ env.CHART_PATH }}/Chart.yaml" ]]; then
            echo "Only Chart.yaml changed. Will create tag but not bump version."
            echo "bumpVersion=false" >> $GITHUB_OUTPUT
            echo "createTag=true" >> $GITHUB_OUTPUT
          else
            echo "Other files changed. Will bump version but not create tag."
            echo "bumpVersion=true" >> $GITHUB_OUTPUT
            echo "createTag=false" >> $GITHUB_OUTPUT
          fi

  bump-version:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: needs.build-and-push.outputs.bumpVersion == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get next version (semver)
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          prefix: "chart-"
          patchList: fix, chore, docs
          noVersionBumpBehavior: current
          skipInvalidTags: true

      - name: Update Chart.yaml version
        if: steps.semver.outputs.next != steps.semver.outputs.current
        run: |
          VERSION="${{ steps.semver.outputs.next }}"
          PLAIN_VERSION="${VERSION#chart-v}"

          # Update Chart.yaml with new version
          yq eval -i ".version = \"$PLAIN_VERSION\"" ${{ env.CHART_PATH }}/Chart.yaml
          cat ${{ env.CHART_PATH }}/Chart.yaml

      - name: Create PR for version bump
        if: steps.semver.outputs.next != steps.semver.outputs.current
        uses: peter-evans/create-pull-request@v8
        id: create_pr
        with:
          token: ${{ secrets.GH_PAT }}
          branch: chore/bump-${{ steps.semver.outputs.next }}
          base: main
          title: "chore(release): bump Helm chart version to ${{ steps.semver.outputs.next }}"
          body: "Automated Helm chart version bump to ${{ steps.semver.outputs.next }}.\n\nThis PR was created automatically by the release workflow."
          commit-message: "chore(release): bump Helm chart version to ${{ steps.semver.outputs.next }}"
          add-paths: |
            ${{ env.CHART_PATH }}/Chart.yaml
          labels: "release, automated-pr"
          draft: false
      - name: Automerge
        if: steps.changes.outputs.skip != 'true' && steps.semver.outputs.next != steps.semver.outputs.current
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: gh pr merge --squash --auto ${{ steps.create_pr.outputs.pull-request-number }}

  create-tag:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: needs.build-and-push.outputs.createTag == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Get version from Chart.yaml
        id: chart-version
        run: |
          VERSION=$(yq eval '.version' ${{ env.CHART_PATH }}/Chart.yaml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Tag
        run: |
          VERSION="${{ steps.chart-version.outputs.version }}"

          git tag "chart-v$VERSION"
          git push origin "chart-v$VERSION"
